jdbc.driver=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://192.168.64.128:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=round&nullCatalogMeansCurrent=true&useSSL=true
jdbc.username=root
jdbc.password=123456
